create a loganalytics sample
Azure-Samples/azure-samples-python-management pull request #90
Opened 2022-04-14 06:48 UTC by kazrael2119

https://github.com/Azure/azure-sdk-for-python/issues/23862

2022-04-18 07:55 UTC, msyyc commented on samples/loganalytics/README.md
> +
python sdk does not support py2.7 anymore

2022-04-18 07:57 UTC, msyyc requested changes
try to use `black` to format code style

2022-04-20 01:15 UTC, BigCat20196 commented on samples/loganalytics/manage_workspace.py
> +    print("List consumption:\n{}\n".format(loganalytics))
This result returns an iterator.

2022-04-20 01:16 UTC, BigCat20196 commented on samples/loganalytics/manage_workspace_with_gov_cloud.py
> +    )
```suggestion
    ).result()
```

2022-05-09 01:15 UTC, msyyc commented on samples/loganalytics/manage_workspace_with_gov_cloud.py
> +    )
```suggestion
    ).result()
```

2022-05-09 01:18 UTC, msyyc commented on samples/loganalytics/manage_workspace.py
> +    )
```suggestion
    ).result()
```

2022-05-09 01:19 UTC, msyyc approved these changes

2022-05-09 01:19 UTC, merged