add service linker sample
Azure-Samples/azure-samples-python-management pull request #91
Opened 2022-04-19 05:22 UTC by ChenTanyi

2022-04-29 07:41 UTC, msyyc requested changes

2022-04-29 07:41 UTC, msyyc commented on samples/servicelinker/README.md
> +    This sample (and the SDK) is compatible with Python 2.7, 3.3, 3.4, 3.5 and 3.6.
python SDK only support >=py3.6 now

2022-04-29 07:41 UTC, msyyc commented on samples/servicelinker/README.md
> +    Install and initialize the virtual environment with the "venv" module on Python 3 (you must install [virtualenv](https://pypi.python.org/pypi/virtualenv) for Python 2.7):
same with up comment

2022-04-29 08:14 UTC, ChenTanyi commented on samples/servicelinker/README.md
> +    This sample (and the SDK) is compatible with Python 2.7, 3.3, 3.4, 3.5 and 3.6.
changed

2022-05-06 02:55 UTC, msyyc approved these changes

2022-05-06 02:55 UTC, merged